on: 
  workflow_dispatch:
  push:
    branches:
      main

jobs:
  ci_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    environment: staging
    name: Run CI
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.13'
        - name: Install dependencies
          run: pip install poetry && poetry install
          working-directory: src/py
        - name: Run formatter
          run: poetry run black . --check
          working-directory: src/py
        - name: Run linting
          run: poetry run pylint .
          working-directory: src/py
        - name: Run unit tests
          run: poetry run pytest .
          working-directory: src/py
  cd_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    needs: ci_job
    environment: staging
    env:
      IMAGE_URL: ${AWS_ECR_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/tetris_container_registry:${TF_VAR_ENVIRONMENT}
    name: Run CD
    steps:
      - uses: actions/checkout@v4
      - name: Apply terraform
        run: terraform apply -auto-approve
        working-directory: src/terraform
      - name: Build Dockerfile for server
        run: docker build -t tetris-server && docker tag tetris-server ${IMAGE_URL} && docker push ${IMAGE_URL}
        working-directory: src/py
